### ISSUE TITLE
import-ldif crashes on OutOfMemoryError

### ISSUE THREAD

**Issue by fyrbach** [WrenSecurity/wrends#49]
## Summary
`import-ldif` crashes with OutOfMemoryError on Java 17.

## Steps To Reproduce ("Repro Steps")

1.  Run setup with sample data creation:

    ```bash
    ./wrends/setup \
      --cli \
      --backendType je \
      --baseDN dc=example,dc=com \
       --ldapPort 1389 \
      --adminConnectorPort 4444 \
      --rootUserDN cn=Directory\ Manager \
      --rootUserPassword password \
      --no-prompt \
      --noPropertiesFile \
      --doNotStart \
      --sampleData 200
    ```

## Expected Result (Behavior You Expected to See)

`import-ldif` successfully imports data without errors.

## Actual Result (Behavior You Saw)

The import stucks on message:

> Importing Automatically-Generated Data (200 Entries) ........

The log in `/tmp/opendj-setup-*.log` contains following error:

```
[24/11/2022:11:56:07 +0100] category=QUICKSETUP seq=72 severity=INFO msg=import-ldif arg list: [/tmp/wrends/bin/import-ldif, --offline, -n, userRoot, -A, /tmp/opendj-install17722320096080648957.template, -s, 0, -F, --noPropertiesFile]
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=73 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=JVM seq=0 severity=INFO msg=Installation Directory:  /tmp/wrends
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=74 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=JVM seq=1 severity=INFO msg=Instance Directory:      /tmp/wrends
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=75 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=JVM seq=2 severity=INFO msg=JVM Information: 17.0.5+8-Ubuntu-2ubuntu1 by Private Build, 64-bit architecture, 3856662528 bytes heap size
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=76 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=JVM seq=3 severity=INFO msg=JVM Host: foobar, running Linux 5.19.0-23-generic amd64, 15426191360 bytes physical memory size, number of processors available 16
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=77 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=JVM seq=4 severity=INFO msg=JVM Arguments: "--add-exports=java.base/sun.security.x509=ALL-UNNAMED", "--add-exports=java.base/sun.security.tools.keytool=ALL-UNNAMED", "-Dorg.opends.server.scriptName=import-ldif"
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=78 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=BACKEND seq=5 severity=FINE msg=JE backend 'userRoot' does not specify the number of cleaner threads: defaulting to 16 threads
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=79 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=BACKEND seq=6 severity=FINE msg=JE backend 'userRoot' does not specify the number of lock tables: defaulting to 37
[24/11/2022:11:56:11 +0100] category=QUICKSETUP seq=80 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:11 +0100] category=BACKEND seq=24 severity=INFO msg=Wren:DS Server 4.0.0-M4-SNAPSHOT starting import (build 20221124115033, Rd7998ffe96597b13df5e2d4af125455f05fbf0da)
[24/11/2022:11:56:12 +0100] category=QUICKSETUP seq=81 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:12 +0100] category=BACKEND seq=25 severity=INFO msg=The amount of free memory available to the import task is 3470996275 bytes. The number of phase one buffers required is 640 buffers
[24/11/2022:11:56:12 +0100] category=QUICKSETUP seq=82 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:12 +0100] category=BACKEND seq=26 severity=INFO msg=Setting DB cache size to 33554432 bytes and phase one buffer size to 4194304 bytes
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=84 severity=WARNING msg=import-ldif error log: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=85 severity=WARNING msg=import-ldif error log:      at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:64)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=86 severity=WARNING msg=import-ldif error log:      at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:363)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=87 severity=WARNING msg=import-ldif error log:      at org.opends.server.backends.pluggable.OnDiskMergeImporter$BufferPool.<init>(OnDiskMergeImporter.java:2890)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=88 severity=WARNING msg=import-ldif error log:      at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.newHeapBufferPool(OnDiskMergeImporter.java:466)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=89 severity=WARNING msg=import-ldif error log:      at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.newBufferPool(OnDiskMergeImporter.java:401)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=90 severity=WARNING msg=import-ldif error log:      at org.opends.server.backends.pluggable.OnDiskMergeImporter$StrategyImpl.importLDIF(OnDiskMergeImporter.java:210)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=91 severity=WARNING msg=import-ldif error log:      at org.opends.server.backends.pluggable.BackendImpl.importLDIF(BackendImpl.java:660)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=92 severity=WARNING msg=import-ldif error log:      at org.opends.server.tools.ImportLDIF.processLocal(ImportLDIF.java:853)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=93 severity=WARNING msg=import-ldif error log:      at org.opends.server.tools.tasks.TaskTool.process(TaskTool.java:246)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=94 severity=WARNING msg=import-ldif error log:      at org.opends.server.tools.ImportLDIF.process(ImportLDIF.java:243)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=95 severity=WARNING msg=import-ldif error log:      at org.opends.server.tools.ImportLDIF.mainImportLDIF(ImportLDIF.java:113)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=96 severity=WARNING msg=import-ldif error log:      at org.opends.server.tools.ImportLDIF.main(ImportLDIF.java:88)
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=83 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:14 +0100] category=BACKEND seq=27 severity=INFO msg=Import LDIF environment close took 0 seconds
[24/11/2022:11:56:14 +0100] category=QUICKSETUP seq=97 severity=INFO msg=import-ldif out log: [24/11/2022:11:56:14 +0100] category=BACKEND seq=28 severity=INFO msg=Flushing data to disk
```

## Environment
- **Product version (include GIT commit ID if using a dev build):** master (d7998ffe96597b13df5e2d4af125455f05fbf0da)
- **Operating system:** Kubuntu 22.10, Linux 5.19.0-23-generic
- **JRE version:** openjdk 17.0.5 2022-10-18
- **Was instance upgraded from a previous version? If so, what version were you using before?** No
- **CPU:** AMD Ryzen 7 PRO 4750U (16 threads)
- **Memory**: 14GB

## Additional Notes

- I did not notice this problem on Java 8 neither 11.
- Manual invocation of `import-ldif` with `-Xmx256m` works.
- It works on some other computers with different CPU and memory size.

**Comment by pavelhoral** [comment]
Seems like this commit is the culprit - https://github.com/WrenSecurity/wrends/commit/997c10c4c5946d76f99f1f2ab9d0786ead1e545c . Current implementation works with MAX memory, but does not subtract USED memory.
